package com.component;

import com.main.Main;
import com.ui.DialogDangNhap;
import com.ui.PanelBanHang;
import com.ui.PanelDanhSachSanPham;
import com.ui.PanelHoaDon;
import com.ui.PanelQuanLyKhachHang;
import com.ui.PanelQuanLyNhanVien;
import com.ui.PanelQuanLyThuocTinh;
import com.ui.PanelThongKe;
import com.ui.PanelQuanLyKhuyenMai;
import com.utils.Auth;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jdk.jshell.Diag;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Thai
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    Main main;
    JPanel menu;
    

    public void setMain(Main main) {
        this.main = main;
        this.menu = (JPanel) main.getPanelMenu();
    }

//    public void updateClock() {
//        Thread time = new Thread() {
//            @Override
//            public void run() {
//                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss   EEEE, d MMM, yyyy");
//                while (true) {
//                    Date day = new Date();
//                    lblDongHo.setText(sdf.format(day));
//                    try {
//                        Thread.sleep(1000);
//                    } catch (Exception e) {
//                        break;
//                    }
//
//                }
//            }
//
//        };
//        time.start();
//    }

    public Menu() {
        initComponents();
        JLabel[] allLabel = {DangXuat, QLHoaDon, QLKhuyenMai, QLNhanVien, QLSanPham, QLThuocTinh, ThongKe, banHang, QLKhachHang};
        for (JLabel label : allLabel) {
            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    label.setForeground(Color.blue);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    label.setForeground(Color.black);
                }

            });
        }
    }

//    public void setMain(Main main) {
//        this.main = main;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        QLKhachHang = new javax.swing.JLabel();
        banHang = new javax.swing.JLabel();
        QLSanPham = new javax.swing.JLabel();
        QLHoaDon = new javax.swing.JLabel();
        QLKhuyenMai = new javax.swing.JLabel();
        QLThuocTinh = new javax.swing.JLabel();
        ThongKe = new javax.swing.JLabel();
        QLNhanVien = new javax.swing.JLabel();
        DangXuat = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa123.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Giày đá bóng Rô con");
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 255, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        QLKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        QLKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/khachhang.png"))); // NOI18N
        QLKhachHang.setText("Khách hàng");
        QLKhachHang.setPreferredSize(new java.awt.Dimension(50, 30));
        QLKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLKhachHangMouseClicked(evt);
            }
        });

        banHang.setBackground(new java.awt.Color(255, 255, 255));
        banHang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        banHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/banhang.png"))); // NOI18N
        banHang.setText("Bán hàng");
        banHang.setPreferredSize(new java.awt.Dimension(50, 30));
        banHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banHangMouseClicked(evt);
            }
        });

        QLSanPham.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        QLSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QLSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sanpham.png"))); // NOI18N
        QLSanPham.setText("Sản phẩm");
        QLSanPham.setPreferredSize(new java.awt.Dimension(50, 30));
        QLSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLSanPhamMouseClicked(evt);
            }
        });

        QLHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        QLHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QLHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        QLHoaDon.setText("Hóa đơn");
        QLHoaDon.setPreferredSize(new java.awt.Dimension(50, 30));
        QLHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLHoaDonMouseClicked(evt);
            }
        });

        QLKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        QLKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/khuyenmai.png"))); // NOI18N
        QLKhuyenMai.setText("Khuyến mãi");
        QLKhuyenMai.setPreferredSize(new java.awt.Dimension(50, 30));
        QLKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLKhuyenMaiMouseClicked(evt);
            }
        });

        QLThuocTinh.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        QLThuocTinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QLThuocTinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thuoctinh.png"))); // NOI18N
        QLThuocTinh.setText("Thuộc tính");
        QLThuocTinh.setPreferredSize(new java.awt.Dimension(50, 30));
        QLThuocTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLThuocTinhMouseClicked(evt);
            }
        });

        ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongke.png"))); // NOI18N
        ThongKe.setText("Thống kê");
        ThongKe.setPreferredSize(new java.awt.Dimension(50, 30));
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeMouseClicked(evt);
            }
        });

        QLNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        QLNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhanvien1.png"))); // NOI18N
        QLNhanVien.setText("Nhân viên");
        QLNhanVien.setPreferredSize(new java.awt.Dimension(50, 30));
        QLNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLNhanVienMouseClicked(evt);
            }
        });

        DangXuat.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        DangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/out.png"))); // NOI18N
        DangXuat.setText("Đăng xuất");
        DangXuat.setPreferredSize(new java.awt.Dimension(50, 30));
        DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(banHang, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DangXuat, QLHoaDon, QLKhachHang, QLKhuyenMai, QLNhanVien, QLSanPham, QLThuocTinh, ThongKe, banHang});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banHang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DangXuat, QLHoaDon, QLKhachHang, QLKhuyenMai, QLNhanVien, QLSanPham, QLThuocTinh, ThongKe, banHang});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        closeMenu();
    }//GEN-LAST:event_jLabel1MousePressed

    private void QLSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLSanPhamMouseClicked
        Main.changeForm(new PanelDanhSachSanPham());
    }//GEN-LAST:event_QLSanPhamMouseClicked

    private void QLHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLHoaDonMouseClicked
        Main.changeForm(new PanelHoaDon());
    }//GEN-LAST:event_QLHoaDonMouseClicked

    private void QLKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLKhuyenMaiMouseClicked
        Main.changeForm(new PanelQuanLyKhuyenMai());
    }//GEN-LAST:event_QLKhuyenMaiMouseClicked


    private void QLThuocTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLThuocTinhMouseClicked
        Main.changeForm(new PanelQuanLyThuocTinh());
    }//GEN-LAST:event_QLThuocTinhMouseClicked

    private void QLKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLKhachHangMouseClicked
        Main.changeForm(new PanelQuanLyKhachHang());
    }//GEN-LAST:event_QLKhachHangMouseClicked

    private void banHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banHangMouseClicked
        Main.changeForm(new PanelBanHang());
    }//GEN-LAST:event_banHangMouseClicked

    private void QLNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLNhanVienMouseClicked
        if (Auth.isManager()) {
            Main.changeForm(new PanelQuanLyNhanVien());
        } else {
            JOptionPane.showMessageDialog(main, "Nhân viên không được sử dụng chức năng này");
        }
    }//GEN-LAST:event_QLNhanVienMouseClicked

    private void ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseClicked
        if (Auth.isManager()) {
            Main.changeForm(new PanelThongKe());
        } else {
            JOptionPane.showMessageDialog(main, "Nhân viên không được sử dụng chức năng này");
        }
    }//GEN-LAST:event_ThongKeMouseClicked

    private void DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMouseClicked
       int hoi = JOptionPane.showConfirmDialog(main, "Bạn chắc chắn muốn Đăng Xuất","Đăng Xuất",JOptionPane.YES_NO_OPTION);
       if(hoi== JOptionPane.YES_OPTION){
      
           DialogDangNhap login = new DialogDangNhap(null, true);
           setMain(main);
           login.setVisible(true);
          
       }
    }//GEN-LAST:event_DangXuatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DangXuat;
    private javax.swing.JLabel QLHoaDon;
    private javax.swing.JLabel QLKhachHang;
    private javax.swing.JLabel QLKhuyenMai;
    private javax.swing.JLabel QLNhanVien;
    private javax.swing.JLabel QLSanPham;
    private javax.swing.JLabel QLThuocTinh;
    private javax.swing.JLabel ThongKe;
    private javax.swing.JLabel banHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void closeMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 310; i >= 0; i--) {
                    try {
                        menu.setSize(i, main.getHeight());
                        Thread.sleep(1);
                        i--;
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
}
